# Generated by Django 3.1 on 2020-08-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_jason', models.CharField(max_length=5000)),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=70)),
                ('state', models.CharField(default='', max_length=70)),
                ('pin_code', models.IntegerField(default='', max_length=50)),
                ('phone', models.IntegerField(default='', max_length=50)),
            ],
        ),
    ]
