# Generated by Django 3.1 on 2020-08-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200819_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items_jason',
            new_name='items_json',
        ),
    ]
